FROM ubuntu:latest
LABEL antonga <antonga@student.wethinkcode.co.za>
##RUN apt-get update &&  apt-get install -y curl openssh-server ca-certificates
##RUN apt-get upgrade -y
##RUN apt-get install -y postfix
##RUN curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash







